### ISSUE TITLE
Pre merge clustergen and other tests

### ISSUE THREAD

**Issue by jayunit100** [vmware-tanzu/tanzu-framework#1005]
**Bug description**
 We don't test clustergen before merge, so we should do prow style bot merging with final merge checks even after lgtm.

- [ x ] Test and Release

**Expected behavior**

Clustergen runs on all commits with head before merge

**Comment by vuil** [comment]
We do run the clustergen tests, but not in a gating fashion, because the verification of the clustergen diffs is a human process, and author/reviewer is supposed to sign off on the posted diffs before the changes are approved.

**Comment by vuil** [comment]
Thanks for the feedback. On pre-merge tests in general: the current situation is temporary: what we are hoping to get to shortly (and until we integrate with a more flexible CI/CD system like prow) is to switch to require all PRs be rebased before being merged. That way there is no need to run additional premerge tests since what is being merged is what has just been tested.
Closing as the other work mentioned is already being tracked.
