### ISSUE TITLE
Allow capability API discover resources when version is unknown

### ISSUE THREAD

**Issue by danniel1205** [vmware-tanzu/tanzu-framework#1294]
(This is used to request new product features)

**Describe the feature request**

As a capability API user, I would like to have an API allows me to discover a resource without specifying the version, because I do not know what version of that resource is currently running in the cluster.

Example: Package plugin would like to use `capdiscovery.Group("packageInstallAPIQuery", "packaging.carvel.dev").WithVersions("xxxx").WithResource("packageinstalls")` to check if `packageInstall` CRD has been deployed. However, the cli code does not know what version of that CRD is current deployed/served. We could put `v1alpha1` as of today and fully rely on the conversion webhook from carvel in the future once they have newer version, but it does not scale if `v1alpha1` gets deprecated (We have to fix it passively and ask user to upgrade their CLI plugin).

A related discussion could be found here: https://github.com/vmware-tanzu/tanzu-framework/pull/1242/files#r761528548

**Describe alternatives you've considered**

Using other APIs(client) to get `packageInstall` CRD, if the result is non-empty then we know `packgeInstall` is available.

**Affected product area (please put an X in all that apply)**

- [x] APIs
- [ ] Addons
- [ ] CLI
- [ ] Docs
- [ ] IAM
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [ ] Test and Release
- [ ] User Experience

**Additional context**

**Comment by danniel1205** [comment]
Loop in @rajathagasthya and @yharish991.

**Comment by rajathagasthya** [comment]
We could add a `WithAnyVersion` option. I can see that being useful, although anyone caring about a resource usually also cares about its version.

**Comment by codegold79** [comment]
While I was working on this issue, I found some incorrect logic/behavior.

When these are provided,
- non-existing resource
- empty string version
- existing group

I expect the result of the findings to be `false` because the resource doesn't exist. 
Actual result:`true`. 

[Line 79 of cluster_gvr.go](https://github.com/vmware-tanzu/tanzu-framework/blob/bb3d775a819e36a6dc9f0713a88130b66fb3bf02/pkg/v1/sdk/capabilities/discovery/cluster_gvr.go#L52) allows empty string version to [continue the loop](https://github.com/vmware-tanzu/tanzu-framework/blob/bb3d775a819e36a6dc9f0713a88130b66fb3bf02/pkg/v1/sdk/capabilities/discovery/cluster_gvr.go#L80) and in effect does not actually check to see if the non-existing resource should be in the unmatched collection.

---

Another bug I found happens when these are provided,
- empty string resource
- existing version
- existing group

I expect the result of the findings to be `false` because there should be no resource that is an empty string.
Actual result: `true`.

The reason for the current result is when an empty string resource is encountered, it [continues the loop](https://github.com/vmware-tanzu/tanzu-framework/blob/bb3d775a819e36a6dc9f0713a88130b66fb3bf02/pkg/v1/sdk/capabilities/discovery/cluster_gvr.go#L95) that checks for unmatched gvrs. It effectively counts the resource as being a match even though no such (empty string) resource was found.

**Comment by codegold79** [comment]
# My plan for this issue has two goals

## Goal 1

The following describes results when the following are provided,
- existing resource
- nil version
- existing group

The current result is an error:

```text
check package availability: cannot check for group and resource existence without version info; use WithVersion method
```

I would like the new error to be,

```text
check package availability: WithVersion method required to check for group and resource existence; use WithVersion("AnyVersion") if version doesn't matter
```

## Goal 2

When the following are provided,
- existing resource
- "AnyVersion" version
- existing group

I expect the following result:

```go
discovery.QueryResult{Found:true, NotFoundReason:""}
```

## Goal 3

Fix the bugs mentioned in [previous comment ](https://github.com/vmware-tanzu/tanzu-framework/issues/1294#issuecomment-1042378813) and write unit tests to ensure logic is correct.
